//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialDesignExtensions.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_cs_cz1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_cs_cz1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialDesignExtensions.Localization.Strings.cs-cz1", typeof(Strings_cs_cz1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Přístup ke složce &apos;{0}&apos; odepřen 的本地化字符串。
        /// </summary>
        internal static string AccessToDirectoryXDenied {
            get {
                return ResourceManager.GetString("AccessToDirectoryXDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zrušit 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zavřít 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vytvořit 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vytvořeno 的本地化字符串。
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plocha 的本地化字符串。
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Podrobnosti 的本地化字符串。
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Složka &apos;{0}&apos; nebyla nalezena 的本地化字符串。
        /// </summary>
        internal static string DirectoryXNotFound {
            get {
                return ResourceManager.GetString("DirectoryXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dokumenty 的本地化字符串。
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disky 的本地化字符串。
        /// </summary>
        internal static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prázdná složka 的本地化字符串。
        /// </summary>
        internal static string EmptyDirectory {
            get {
                return ResourceManager.GetString("EmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soubory 的本地化字符串。
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Velikost souboru 的本地化字符串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Složky 的本地化字符串。
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Naposledy otevřeno 的本地化字符串。
        /// </summary>
        internal static string LastAccess {
            get {
                return ResourceManager.GetString("LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Naposledy upraveno 的本地化字符串。
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Místní disk 的本地化字符串。
        /// </summary>
        internal static string LocalDrive {
            get {
                return ResourceManager.GetString("LocalDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dlouhé cesty nejsou podporovány 的本地化字符串。
        /// </summary>
        internal static string LongPathsAreNotSupported {
            get {
                return ResourceManager.GetString("LongPathsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximalizovat 的本地化字符串。
        /// </summary>
        internal static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimalizovat 的本地化字符串。
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hudba 的本地化字符串。
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nový název složky 的本地化字符串。
        /// </summary>
        internal static string NewDirectoryName {
            get {
                return ResourceManager.GetString("NewDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Žádné vybrané složky 的本地化字符串。
        /// </summary>
        internal static string NoSelectedDirectories {
            get {
                return ResourceManager.GetString("NoSelectedDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Žádné vybrané soubory 的本地化字符串。
        /// </summary>
        internal static string NoSelectedFiles {
            get {
                return ResourceManager.GetString("NoSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Otevřít 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Otevřít soubor 的本地化字符串。
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obrázky 的本地化字符串。
        /// </summary>
        internal static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Odstranit 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obnovit 的本地化字符串。
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uložit 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uložit soubor 的本地化字符串。
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hledat 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vybrat 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vybrat složku 的本地化字符串。
        /// </summary>
        internal static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Výběr 的本地化字符串。
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Název složky je neplatný 的本地化字符串。
        /// </summary>
        internal static string TheDirectoryNameIsInvalid {
            get {
                return ResourceManager.GetString("TheDirectoryNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Název složky nesmí být prázdný 的本地化字符串。
        /// </summary>
        internal static string TheDirectoryNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("TheDirectoryNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Složka &apos;{0}&apos; již existuje 的本地化字符串。
        /// </summary>
        internal static string TheDirectoryXAlreadyExists {
            get {
                return ResourceManager.GetString("TheDirectoryXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uživatel 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Videa 的本地化字符串。
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
