//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialDesignExtensions.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_de1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_de1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialDesignExtensions.Localization.Strings.de1", typeof(Strings_de1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Kein Zugriff auf den Ordner &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string AccessToDirectoryXDenied {
            get {
                return ResourceManager.GetString("AccessToDirectoryXDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abbrechen 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Schließen 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erstellen 的本地化字符串。
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erstellt 的本地化字符串。
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop 的本地化字符串。
        /// </summary>
        internal static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordner &quot;{0}&quot; nicht gefunden 的本地化字符串。
        /// </summary>
        internal static string DirectoryXNotFound {
            get {
                return ResourceManager.GetString("DirectoryXNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dokumente 的本地化字符串。
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datenträger 的本地化字符串。
        /// </summary>
        internal static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leerer Ordner 的本地化字符串。
        /// </summary>
        internal static string EmptyDirectory {
            get {
                return ResourceManager.GetString("EmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dateien 的本地化字符串。
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dateigröße 的本地化字符串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordner 的本地化字符串。
        /// </summary>
        internal static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Letzter Zugriff 的本地化字符串。
        /// </summary>
        internal static string LastAccess {
            get {
                return ResourceManager.GetString("LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geändert 的本地化字符串。
        /// </summary>
        internal static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lokaler Datenträger 的本地化字符串。
        /// </summary>
        internal static string LocalDrive {
            get {
                return ResourceManager.GetString("LocalDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lange Pfade werden nicht unterstützt 的本地化字符串。
        /// </summary>
        internal static string LongPathsAreNotSupported {
            get {
                return ResourceManager.GetString("LongPathsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximieren 的本地化字符串。
        /// </summary>
        internal static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimieren 的本地化字符串。
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Musik 的本地化字符串。
        /// </summary>
        internal static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neuer Ordnername 的本地化字符串。
        /// </summary>
        internal static string NewDirectoryName {
            get {
                return ResourceManager.GetString("NewDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keine ausgewählten Ordner 的本地化字符串。
        /// </summary>
        internal static string NoSelectedDirectories {
            get {
                return ResourceManager.GetString("NoSelectedDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keine ausgewählten Dateien 的本地化字符串。
        /// </summary>
        internal static string NoSelectedFiles {
            get {
                return ResourceManager.GetString("NoSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Öffnen 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datei öffnen 的本地化字符串。
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilder 的本地化字符串。
        /// </summary>
        internal static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entfernen 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verkleinern 的本地化字符串。
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speichern 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Datei speichern 的本地化字符串。
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suchen 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auswählen 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordner auswählen 的本地化字符串。
        /// </summary>
        internal static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auswahl 的本地化字符串。
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Der Ordnername ist ungültig 的本地化字符串。
        /// </summary>
        internal static string TheDirectoryNameIsInvalid {
            get {
                return ResourceManager.GetString("TheDirectoryNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Der Ordername darf nicht leer sein 的本地化字符串。
        /// </summary>
        internal static string TheDirectoryNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("TheDirectoryNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Der Ordner &quot;{0}&quot; existiert bereits 的本地化字符串。
        /// </summary>
        internal static string TheDirectoryXAlreadyExists {
            get {
                return ResourceManager.GetString("TheDirectoryXAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Benutzer 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Videos 的本地化字符串。
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
